### ISSUE TITLE
v0.4.2 is still broken

### ISSUE THREAD

**Issue by julienrbrt** [cosmos/evm#767]
When updating the Ignite EVM App from 2d3df2ba510c to `v0.4.2`, I am still getting:

```sh
[IGNITE] /var/cache/go/github.com/cosmos/evm@v0.4.2/x/vm/statedb/statedb.go:40:20: cannot
[IGNITE] use &StateDB{} (value of type *StateDB) as
[IGNITE] "github.com/ethereum/go-ethereum/core/vm".StateDB value in variable declaration:
[IGNITE] *StateDB does not implement "github.com/ethereum/go-ethereum/core/vm".StateDB
[IGNITE] (missing method IsStorageEmpty)
[IGNITE] : exit status 1
```

This means, this commit is still missing: https://github.com/cosmos/evm/pull/490 / https://github.com/cosmos/evm/commit/1f22f1971d4417ced436ebee3281859034a48c24

Using: https://github.com/cosmos/go-ethereum/releases/tag/v1.16.2-cosmos-1 instead of a random commit like in https://github.com/cosmos/evm/blob/v0.4.2/go.mod#L275-L276C67 -> https://github.com/cosmos/go-ethereum/compare/2fc7571efa91...v1.16.2-cosmos-1

Please backport this PR and re-tag v0.4.x
